services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    container_name: sql
  api:
    ports:
      - "8080:8080"
    depends_on:
      - sql
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api